import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import Header from '@/components/ui/header/Header'
import Footer from '@/components/ui/footer/Footer'
import Providers from '@/context/providers'
import './globals.css'

const roboto_mono = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Maikol Vitta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${roboto_mono.className} antialiased min-w-min dark:bg-dark-mode`}
      >
        <Providers>
          <Header className='bg-white dark:bg-dark-mode w-full h-[60px] transition shadow-md dark:shadow-slate-800' />

          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
